# SVG To Gmsh Configuration

## coil current directions
# Positive current flows out of the page.
# Counting order: Top to bottom, left to right.
coil_currents: 
  coil_1: 1
  coil_2: -1
  coil_3: 1
  coil_4: -1
  coil_5: 1
  coil_6: -1
  coil_7: 1
  coil_8: -1
  coil_9: 1
  coil_10: -1
  coil_11: 1
  coil_12: -1

## mesh settings
# Set the mesh size for Gmsh
mesh_size: 0.1